name: Build g10k container image.

on:
  push:
    branches: ["main"]
    paths:
      - "g10k/**"
      - ".github/workflows/g10k.yml"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Generate container metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/obmondo/g10k
          tags: |
            type=raw,value=latest
            type=semver,pattern={{version}},value=v0.9.9
          flavor: |
            latest=false

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push container image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: "./g10k/Dockerfile"
          context: .
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64
